### ISSUE TITLE
Can't deploy the program

### ISSUE THREAD

**Issue by kavv007** [jackchurch/Tafe20S202#1]
The button that I used to run the program has been changed. It used to be 'Local Machine' but now it's showing as 'Device'. The program throws up the following error when I try to run it

![image](https://user-images.githubusercontent.com/25866021/93728792-c0056500-fc00-11ea-925e-394aa8a29c45.png)

**Comment by Ulziitugsa** [comment]
Hey Kavv007,
It is because you're trying to compile it on ARM.
On the top menu if you change the ARM to x86 it should return back to 'Local Machine'.
