### ISSUE TITLE
I'm having Deployment issues 

### ISSUE THREAD

**Issue by DeliciousBiscuits** [jackchurch/Tafe20S202#2]
![92212219-cb525400-eed0-11ea-9d28-9f3671b8484b](https://user-images.githubusercontent.com/67183399/93728907-4326bb00-fc01-11ea-83ef-63e087874c8a.png)

**Comment by jackchurch** [comment]
Hi Kizzie, 

Applications are unable to run on file systems that are formatted as exFat. This is a limitation of Microsoft Windows.

To get the program to run; please move the files onto a hard disk that is formatted with NTFS.

Please let me know if you require any more help with this.

Regards
Jack
