### ISSUE TITLE
Unable to update footer in Wiki

### ISSUE THREAD

**Issue by jackchurch** [jackchurch/Tafe20S202#4]
I'm unable to find the footer edit button for the wiki.

**Comment by kavv007** [comment]
Hi jackchurch,

Navigate to the Wiki and find the edit button I have highlighted in the screenshot below. It should allow you to edit the footer.

![image](https://user-images.githubusercontent.com/25866021/93730840-8ab14500-fc09-11ea-974f-e4b5d4edee07.png)

Regards,
kavvv007

**Comment by jackchurch** [comment]
Thanks.
